const colors = {
  light: {
    text: "#1C2236",
    tint: "#5168B4",
    background: "#F4F6FD",
    foreground: "#1C2236",
    card: "#FFFFFF",
    cardForeground: "#1C2236",
    primary: "#5168B4",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF0FB",
    secondaryForeground: "#3D4E8A",
    muted: "#F0F2FA",
    mutedForeground: "#7480A0",
    accent: "#3AAFA9",
    accentForeground: "#FFFFFF",
    destructive: "#E85555",
    destructiveForeground: "#FFFFFF",
    border: "#E4E8F5",
    input: "#E4E8F5",
    riskLow: "#3DAD7A",
    riskModerate: "#F09736",
    riskHigh: "#E85555",
    teal: "#3AAFA9",
    purple: "#7C5CBF",
    warm: "#F2A65A",
    navy: "#1C2236",
    lavender: "#DDE3F8",
    blush: "#F2EEFF",
    softGreen: "#E6F7F2",
    softOrange: "#FEF4E8",
    softRed: "#FDECEC",
  },
  radius: 16,
};

export default colors;
